/** @type {Record<string, unknown>} */
export const vi = {
  brand: "DriveGo",
  brandHub: "DriveHub",
  nav: {
    home: "Trang chủ",
    pricing: "Bảng giá",
    docs: "Tài liệu",
    lookup: "Tra cứu",
    register: "Đăng ký",
    login: "Đăng nhập",
    more: "Thêm",
    moreGroupApp: "Ứng dụng",
    history: "Lịch sử",
    exam: "Thi thử",
    theory: "Học lý thuyết",
    schedule: "Lịch thi",
    studentDashboard: "Tổng quan",
    forgotPassword: "Quên mật khẩu",
    upgrade: "Nâng cấp",
    profile: "Hồ sơ",
    studyCalendar: "Lịch học",
    aiChat: "AI Chat",
    notifications: "Thông báo",
    centerRegister: "Đăng ký trung tâm",
    adminDashboard: "Quản trị TT",
    features: "Tính năng",
    support: "Hỗ trợ",
    courses: "Khóa học",
    exams: "Kỳ thi",
    contact: "Liên hệ",
  },
  common: {
    loading: "Đang tải...",
    viewAll: "Xem tất cả",
    viewDetail: "Xem chi tiết",
    registerNow: "Đăng ký ngay",
    startFree: "Bắt đầu miễn phí",
    viewDemo: "Xem demo",
    send: "Gửi",
    search: "Tìm kiếm",
    confirm: "Xác nhận",
    cancel: "Hủy",
    save: "Lưu",
    edit: "Chỉnh sửa",
    backToLogin: "Quay lại trang đăng nhập",
  },
  footer: {
    tagline:
      "Hệ thống đào tạo và luyện thi bằng lái xe hàng đầu Việt Nam. Giúp bạn tự tin cầm lái.",
    platform: "Nền tảng",
    support: "Hỗ trợ",
    contact: "Liên hệ",
    copyright: "© 2024 DriveGo. Bảo lưu mọi quyền.",
    terms: "Điều khoản sử dụng",
    privacy: "Chính sách bảo mật",
  },
  pages: {
    home: {
      badge: "Nền tảng học lái xe thông minh",
      title: "Nền Tảng Học Lái Xe",
      titleHighlight: "Thế Hệ Mới",
      subtitle:
        "Hệ thống học tập thông minh và quản lý đào tạo lái xe kỹ thuật số tiên tiến nhất. Tối ưu hóa quy trình và nâng cao tỷ lệ đỗ với công nghệ AI.",
      featuresTitle: "Tại sao chọn DriveGo?",
      feature1: "Học mọi lúc mọi nơi",
      feature2: "Đề thi cập nhật",
      feature3: "Phân tích hiệu quả",
      feature4: "Bảo mật tuyệt đối",
    },
    login: {
      title: "Chào mừng trở lại",
      subtitle: "Đăng nhập để tiếp tục quản lý hành trình của bạn",
      email: "Email",
      emailPlaceholder: "nhap@email.com",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu của bạn",
      remember: "Ghi nhớ đăng nhập",
      forgot: "Quên mật khẩu?",
      submit: "Đăng nhập",
      noAccount: "Bạn chưa có tài khoản?",
      signup: "Đăng ký ngay",
      orContinue: "Hoặc tiếp tục với",
    },
    register: {
      title: "Đăng ký tài khoản",
      subtitle: "Hoàn thành form bên dưới để bắt đầu học cùng DriveGo.",
      tabStudent: "Học viên",
      tabCenter: "Trung tâm đào tạo",
      fullName: "Họ và tên",
      email: "Email",
      password: "Mật khẩu",
      confirmPassword: "Xác nhận mật khẩu",
      submit: "Tạo tài khoản",
      hasAccount: "Đã có tài khoản?",
      login: "Đăng nhập ngay",
    },
    forgotPassword: {
      title: "Quên mật khẩu?",
      subtitle:
        "Đừng lo lắng, chúng tôi sẽ giúp bạn. Nhập email liên kết với tài khoản để nhận liên kết đặt lại mật khẩu.",
      email: "Email",
      submit: "Gửi yêu cầu",
    },
    pricing: {
      title: "Chọn loại bằng",
      titleHighlight: "phù hợp với bạn",
      subtitle: "Gói cực hợp mọi nhu cầu — từ ôn lý thuyết đến khóa B2 trọn gói.",
      popular: "Phổ biến nhất",
      consultTitle: "Bạn cần tư vấn thêm?",
      consultSubtitle: "Để lại số điện thoại, đội ngũ sẽ liên hệ trong 5 phút.",
    },
    docs: {
      title: "Trung tâm",
      titleHighlight: "Tài Liệu & Hướng Dẫn",
      subtitle:
        "Tra cứu quy trình, mẹo học lý thuyết và kinh nghiệm thi sát hạch mới nhất.",
      searchPlaceholder: "Tìm kiếm tài liệu, hướng dẫn...",
      toc: "Mục lục",
      support: "Cần hỗ trợ?",
      supportCta: "Nhắn tin ngay",
      downloadPdf: "Tải PDF hướng dẫn",
      faq: "Câu hỏi thường gặp",
    },
    lookup: {
      title: "Tra cứu thông tin",
      titleHighlight: "nhanh chóng",
      subtitle: "Hệ thống tra cứu kết quả, lịch sát hạch và thông tin học viên theo thời gian thực.",
      placeholder: "Số CCCD / Mã học viên",
      submit: "Tra cứu",
      resultTitle: "Kết quả tra cứu",
      passed: "Đạt kết quả",
    },
    history: {
      title: "Lịch Sử Làm Bài Thi Của Bạn",
      subtitle: "Theo dõi quá trình luyện thi và tối ưu điểm số trước kỳ thi chính thức.",
      totalExams: "Tổng bài thi",
      passRate: "Tỷ lệ đạt",
      bestScore: "Điểm cao nhất",
      reviewHint: "Gợi ý ôn tập",
      startReview: "Bắt đầu ôn tập ngay",
    },
    exam: {
      questionLabel: "Câu",
      timeLeft: "Thời gian còn lại",
      tempResult: "Kết quả tạm tính",
      correct: "Đúng",
      wrong: "Sai",
    },
    schedule: {
      title: "Chọn Lịch Thi",
      titleHighlight: "Phù Hợp Với Bạn",
      subtitle:
        "Hệ thống đăng ký sát hạch lái xe trực tuyến. Nhanh chóng, minh bạch và thuận tiện.",
      slotsTitle: "Ca thi ngày",
      available: "Còn chỗ",
      full: "Đã đầy suất đăng ký",
    },
    studentDashboard: {
      title: "Tổng quan",
      statProgress: "Tiến độ học tập",
      statSessions: "Số buổi học tháng",
      statScore: "Điểm trung bình",
      statStatus: "Trạng thái",
      currentLesson: "Bài học hiện tại",
      continue: "Tiếp tục học",
      reviewTips: "Gợi ý ôn tập",
    },
    theory: {
      title: "Học Lý Thuyết",
      titleHighlight: "Mọi Lúc, Mọi Nơi",
      subtitle: "Hệ thống học thông minh với hơn 600 câu hỏi mới nhất.",
      roadmap: "Lộ trình học tập",
      startNow: "Bắt đầu học ngay",
    },
    profile: {
      title: "Hồ sơ của bạn",
      subtitle: "Quản lý thông tin tài khoản và xem lịch sử học",
      changePassword: "Đổi mật khẩu",
      active: "Đang hoạt động",
      recentActivity: "Lịch sử hoạt động gần đây",
    },
    upgrade: {
      title: "Nâng Cấp",
      titleHighlight: "Tài Khoản",
      subtitle: "Mở khóa toàn bộ tính năng Premium: AI, thi không giới hạn, hỗ trợ 24/7.",
      free: "Miễn phí",
      premium: "Premium",
      upgradeNow: "Nâng cấp ngay",
      paymentTitle: "Phương thức thanh toán",
      paySecure: "Thanh toán an toàn",
    },
    notifications: {
      title: "Thông báo",
      subtitle: "Cập nhật những tin tức mới nhất về lộ trình của bạn",
      all: "Tất cả",
      unread: "Chưa đọc",
      important: "Quan trọng",
    },
    centerRegister: {
      title: "Hợp tác Đào tạo",
      subtitle: "Đăng ký trở thành đối tác trung tâm trên hệ sinh thái DriveGo.",
      section1: "Thông tin trung tâm",
      section2: "Người đại diện",
      section3: "Tài khoản đăng nhập",
      submit: "Đăng ký trung tâm",
    },
    adminDashboard: {
      title: "Tổng quan trung tâm",
    },
    aiChat: {
      title: "DriveGo AI",
      newChat: "Trò chuyện mới",
      placeholder: "Hỏi DriveGo về luật và thông tin cho lái xe trẻ",
      send: "Gửi",
    },
    studyCalendar: {
      title: "Lịch Học & Thi",
      eventDetail: "Chi tiết sự kiện",
      upcoming: "Sắp tới",
      checkIn: "Điểm danh ngay",
    },
  },
}
