import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs"
import { dirname, resolve } from "path"
import { fileURLToPath } from "url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")

const FIREBASE_KEY_MAP = {
  apiKey: "VITE_FIREBASE_API_KEY",
  authDomain: "VITE_FIREBASE_AUTH_DOMAIN",
  projectId: "VITE_FIREBASE_PROJECT_ID",
  storageBucket: "VITE_FIREBASE_STORAGE_BUCKET",
  messagingSenderId: "VITE_FIREBASE_MESSAGING_SENDER_ID",
  appId: "VITE_FIREBASE_APP_ID",
  measurementId: "VITE_FIREBASE_MEASUREMENT_ID",
}

function parseEnvFile(content) {
  /** @type {Record<string, string>} */
  const env = {}
  for (const line of content.split("\n")) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith("#")) continue
    const eq = trimmed.indexOf("=")
    if (eq === -1) continue
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim()
  }
  return env
}

function formatEnvFile(lines) {
  return `${lines.join("\n").replace(/\n+$/, "")}\n`
}

function parseFirebaseTxt(filePath) {
  if (!existsSync(filePath)) {
    return {}
  }

  const content = readFileSync(filePath, "utf8")
  /** @type {Record<string, string>} */
  const values = {}

  for (const [jsKey, envKey] of Object.entries(FIREBASE_KEY_MAP)) {
    const match = content.match(new RegExp(`${jsKey}:\\s*"([^"]+)"`))
    if (match) {
      values[envKey] = match[1]
    }
  }

  return values
}

function findServiceAccountRelativePath() {
  const jsonFile = readdirSync(root).find(
    (name) => name.includes("firebase-adminsdk") && name.endsWith(".json"),
  )
  return jsonFile ? `../${jsonFile}` : null
}

function loadExistingEnv(relativePath) {
  const filePath = resolve(root, relativePath)
  if (!existsSync(filePath)) {
    return {}
  }
  return parseEnvFile(readFileSync(filePath, "utf8"))
}

function writeEnv(relativePath, lines) {
  const filePath = resolve(root, relativePath)
  writeFileSync(filePath, formatEnvFile(lines), "utf8")
  return filePath
}

function mergeDefined(base, patch) {
  const next = { ...base }
  for (const [key, value] of Object.entries(patch)) {
    if (value !== undefined && value !== "") {
      next[key] = value
    }
  }
  return next
}

const firebaseTxtPath = resolve(root, "firebase.txt")
const firebaseWeb = parseFirebaseTxt(firebaseTxtPath)
const serviceAccountPath = findServiceAccountRelativePath()
const projectId = firebaseWeb.VITE_FIREBASE_PROJECT_ID

const frontendDefaults = {
  VITE_API_URL: "http://localhost:3000/api",
  ...firebaseWeb,
}

const frontendEnv = mergeDefined(frontendDefaults, loadExistingEnv("frontend/.env"))

writeEnv("frontend/.env", [
  "# Auto-generated by npm run setup:env — edit values here, not in source code",
  `VITE_API_URL=${frontendEnv.VITE_API_URL}`,
  "",
  "# Firebase Web (Google Sign-in)",
  `VITE_FIREBASE_API_KEY=${frontendEnv.VITE_FIREBASE_API_KEY ?? ""}`,
  `VITE_FIREBASE_AUTH_DOMAIN=${frontendEnv.VITE_FIREBASE_AUTH_DOMAIN ?? ""}`,
  `VITE_FIREBASE_PROJECT_ID=${frontendEnv.VITE_FIREBASE_PROJECT_ID ?? ""}`,
  `VITE_FIREBASE_STORAGE_BUCKET=${frontendEnv.VITE_FIREBASE_STORAGE_BUCKET ?? ""}`,
  `VITE_FIREBASE_MESSAGING_SENDER_ID=${frontendEnv.VITE_FIREBASE_MESSAGING_SENDER_ID ?? ""}`,
  `VITE_FIREBASE_APP_ID=${frontendEnv.VITE_FIREBASE_APP_ID ?? ""}`,
  ...(frontendEnv.VITE_FIREBASE_MEASUREMENT_ID
    ? [`VITE_FIREBASE_MEASUREMENT_ID=${frontendEnv.VITE_FIREBASE_MEASUREMENT_ID}`]
    : []),
])

const backendDefaults = {
  PORT: "3000",
  CORS_ORIGIN: "http://localhost:5173",
  DATABASE_URL: "postgresql://postgres:YOUR_PASSWORD@localhost:5432/DriveGo",
  JWT_SECRET: "change-me",
  ...(projectId ? { FIREBASE_PROJECT_ID: projectId } : {}),
  ...(serviceAccountPath ? { GOOGLE_APPLICATION_CREDENTIALS: serviceAccountPath } : {}),
}

const backendEnv = mergeDefined(backendDefaults, loadExistingEnv("backend/.env"))

writeEnv("backend/.env", [
  "# Auto-generated by npm run setup:env — edit secrets here",
  `PORT=${backendEnv.PORT}`,
  `CORS_ORIGIN=${backendEnv.CORS_ORIGIN}`,
  `DATABASE_URL=${backendEnv.DATABASE_URL}`,
  `JWT_SECRET=${backendEnv.JWT_SECRET}`,
  "",
  "# Firebase Admin (Google Sign-in)",
  `FIREBASE_PROJECT_ID=${backendEnv.FIREBASE_PROJECT_ID ?? ""}`,
  `GOOGLE_APPLICATION_CREDENTIALS=${backendEnv.GOOGLE_APPLICATION_CREDENTIALS ?? ""}`,
  "",
  "# SePay — https://my.sepay.vn/webhooks",
  `SEPAY_PAYMENT_CODE_PREFIX=${backendEnv.SEPAY_PAYMENT_CODE_PREFIX ?? "DG"}`,
  `SEPAY_WEBHOOK_API_KEY=${backendEnv.SEPAY_WEBHOOK_API_KEY ?? ""}`,
  `SEPAY_BANK_NAME=${backendEnv.SEPAY_BANK_NAME ?? ""}`,
  `SEPAY_BANK_ACCOUNT=${backendEnv.SEPAY_BANK_ACCOUNT ?? ""}`,
  `SEPAY_ACCOUNT_HOLDER=${backendEnv.SEPAY_ACCOUNT_HOLDER ?? ""}`,
  "",
  "# Google Gemini — AI Chat",
  `GEMINI_API_KEY=${backendEnv.GEMINI_API_KEY ?? ""}`,
  `GEMINI_MODEL=${backendEnv.GEMINI_MODEL ?? "gemini-2.0-flash"}`,
])

const databaseEnv = mergeDefined(
  { DATABASE_URL: backendEnv.DATABASE_URL },
  loadExistingEnv("database/.env"),
)

writeEnv("database/.env", [
  "# Synced from backend/.env by npm run setup:env",
  `DATABASE_URL=${databaseEnv.DATABASE_URL}`,
])

console.log("Environment files updated:")
console.log(`  - ${resolve(root, "frontend/.env")}`)
console.log(`  - ${resolve(root, "backend/.env")}`)
console.log(`  - ${resolve(root, "database/.env")}`)

if (!existsSync(firebaseTxtPath)) {
  console.warn("\nWarning: firebase.txt not found — frontend Firebase vars may be empty.")
} else if (!firebaseWeb.VITE_FIREBASE_API_KEY) {
  console.warn("\nWarning: could not parse firebase.txt — check firebaseConfig format.")
}

if (!serviceAccountPath) {
  console.warn("\nWarning: no *firebase-adminsdk*.json in repo root — set GOOGLE_APPLICATION_CREDENTIALS manually.")
}
